### PR TITLE
Fix the English translation of 疏排

### PR DESCRIPTION
**Pull request by xfq**
Currently, 疏排 is "loose setting" in https://w3c.github.io/clreq/#increased_inter_character_spacing , and "Fixed inter-character spacing setting" in the Glossary. This PR makes the English wording consistent and fixes the wording in the glossary description.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/pull/256.html" title="Last updated on Feb 18, 2020, 5:57 AM UTC (db6064e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/256/4be3fec...db6064e.html" title="Last updated on Feb 18, 2020, 5:57 AM UTC (db6064e)">Diff</a>

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/pull/256.html" title="Last updated on Dec 18, 2021, 6:09 AM UTC (d4a645a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/256/658bda4...d4a645a.html" title="Last updated on Dec 18, 2021, 6:09 AM UTC (d4a645a)">Diff</a>

### CODE REVIEW

**Comment by r12a** [comment]
Sounds like you're defining 'tracking' (aka letter-spacing)?

**Comment by xfq** [comment]
@r12a 疏排 means text setting with extra (and even, unless there is [line adjustment](https://github.com/w3c/clreq/issues/255)) inter-character spacing in addition to the default spacing (which is zero, i.e., solid setting) between adjacent character frames, so this term itself does not mean tracking. We use the term 字距 for tracking.

**Comment by r12a** [comment]
How is tracking different?  The explanation you gave for 疏排 sounds exactly like what i'd expect for a definition of tracking. See, for example, how it is explained at https://drafts.csswg.org/css-text-3/#letter-spacing-property. What am i missing?

**Comment by xfq** [comment]
> How is tracking different?  The explanation you gave for 疏排 sounds exactly like what i'd expect for a definition of tracking. See, for example, how it is explained at https://drafts.csswg.org/css-text-3/#letter-spacing-property. What am i missing?

Tracking can be positive, zero, or negative, but 疏排 means the state when tracking is greater than zero.

**Comment by xfq** [comment]
Taking jlreq as an example, I think 疏排 is similar to [アキ組](https://w3c.github.io/jlreq/#term.fixed-inter-character-spacing), and 字距 is similar to [字間](https://w3c.github.io/jlreq/#term.inter-character-space). So another way to fix this issue is to change "loose setting" in https://w3c.github.io/clreq/#increased_inter_character_spacing to "fixed inter-character spacing", and change "Fixed inter-character spacing setting" in the Glossary to "fixed inter-character spacing" to match jlreq.

**Comment by xfq** [comment]
@r12a In our meeting yesterday, we [decided](https://www.w3.org/2020/03/05-clreq-minutes.html#t02) to use my current text in this PR. Have you understood 疏排 after reading https://github.com/w3c/clreq/pull/256#issuecomment-590825209 ?

(If you have better suggestions to express the state when tracking is greater than zero, please feel free to suggest it.)

**Comment by xfq** [comment]
Discussions in yesterday's meeting: https://www.w3.org/2021/12/17-clreq-minutes.html#t03

**Comment by xfq** [comment]
Merging per https://www.w3.org/2022/01/21-clreq-minutes.html#t07

**Pull request merged**
