### PR TITLE
Refine scripts and styles for appendix tables, etc

### PR DESCRIPTION
**Pull request by ethantw**
## Preview
<https://ethantw.github.io/clreq/>

## Scripts
- Refactor the language-switching script, which now allows one to switch back to multilingual version or other language after the first switch.

## Tables 
- Refine styles for tables of glossary and punctuation marks.
- Separate the table of punctuation marks into smaller ones by their natures (點號, 標號, brackets, etc).
- Add a full table of characters of punctuation marks indicating their layout properties (prohibition, etc).

## TC/SC indicators
- Adjust their left margin in headings.
- Lighter colours to avoid visual interfering.
- Have ones of block elements (`p`, `ol`, `ul`, etc) hang outside their context, so they won’t look too much like quotations or notes.
- Avoid line breaks in headings if possible.

## Others
- Minor typo fixes.

### CODE REVIEW

**Comment by ryukeikun** [comment]
These are all good improvements, I have no further comments for this! Great job!

**Review by r12a — COMMENTED** [review]
The new functionality of the language switch is useful. I tested it briefly, and it seems to work. However i can no longer understand the all the Javascript that does the work, so if we stick with these changes you'll have to do the maintenance from now on.  

I have no particular view wrt the changes to the punctuation table, other than that it looks neater, and the following:
1. in A3 and 201C the right most column has text that seems to overlap more than one row but has a grey divider line running through it.
2. in the first column, at first glance, lots of chinese names appear to be missing – perhaps we need a better title for that column rather than Name. Eg Type?
3. i didn't have time to examine in detail all the changes to the css style sheet, because there are lots of formatting changes obscuring the diff.

hth

**Comment by r12a** [comment]
@ethantw A3 means Appendix 3, 201C is the Unicode code point for the row where the problem occurred.

**Comment by ethantw** [comment]
@r12a 

> The new functionality of the language switch is useful. I tested it briefly, and it seems to work. However i can no longer understand the all the Javascript that does the work, so if we stick with these changes you'll have to do the maintenance from now on.

Sure, I can do the maintenance. :)

> in A3 and 201C the right most column has text that seems to overlap more than one row but has a grey divider line running through it.

The corner brackets (U+300C-F) and the quotation marks (U+2018-9, U+201C-D) represent the quotation marks in zh-Hant and zh-Hans respectively. Hence they share the same Chinese name whilst the details are described in different notes.

> in the first column, at first glance, lots of chinese names appear to be missing – perhaps we need a better title for that column rather than Name. Eg Type?

The only names that are missing are the unofficial brackets in A.3 (starting from U+3010 to the end), which has different usage in different publications. I think the current status is enough.

**Pull request merged**
