### PR TITLE
Format character sizing information into tables

### PR DESCRIPTION
**Pull request by huijing**
@ethantw I know you haven't merged #143 to the main branch yet, so I pulled from your refine-styles branch and applied my changes on top of that. I made some of the generic appendix table styles apply to all tables as well. Please let me know if that's ok.

### CODE REVIEW

**Comment by xfq** [comment]
@ethantw Is it OK to merge this now?

**Comment by ethantw** [comment]
@ryukeikun Can you take a look at this PR? I think you relate to the details of font sizes more. Thanks!

**Comment by ryukeikun** [comment]
Actually I am considering to rewrite the paragraph about font size, but it takes some more time. But for the format, I think the table view is OK.

**Comment by xfq** [comment]
So I'll merge this PR for now. Thanks!

**Pull request merged**
