### PR TITLE
Move editors to authors

### LINKED ISSUE #601: Move editors to authors
After discussing with @r12a, we need to move editors who are not in the Internationalisation Working Group to *authors* to pass the latest [Pubrules](https://www.w3.org/pubrules/doc/rules?profile=DNOTE#editorSection):

> Editors must be participating in the group producing the document at the time of its publication.

### PR DESCRIPTION
**Pull request by xfq**
Fix #601.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/pull/603.html" title="Last updated on Apr 16, 2024, 7:34 AM UTC (6830390)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/603/2553c7d...6830390.html" title="Last updated on Apr 16, 2024, 7:34 AM UTC (6830390)">Diff</a>

### CODE REVIEW

**Comment by r12a** [comment]
```
Former editors:
    [李安琪 (Angel LI)](mailto:angel@w3.org) (W3C) 
    [梁海 (Hai LIANG)](mailto:lianghai@gmail.com) (特邀专家 / Invited Expert) 
    [吴小倩 (Xiaoqian WU)](mailto:xiaoqian@w3.org) (W3C) 
    [张爱杰 (Aijie ZHANG)](mailto:zhangaijie_yjs@139.com) (中国移动通信集团公司 / China Mobile)

```

Of these folks, i think Angel was involved in working on translations, but otherwise no-one provided content or editorial work (i could be wrong).  It looks a little odd to me to see them all listed as former editors. What do you think?

**Comment by xfq** [comment]
Discussions in clreq meetings:

* https://www.w3.org/2024/02/21-clreq-minutes.html#t03
* https://www.w3.org/2024/03/27-clreq-minutes.html#t04
* https://www.w3.org/2024/05/08-clreq-minutes.html#t03

Discussions in i18n WG meeting: https://www.w3.org/2024/02/29-i18n-minutes.html#t07

**Comment by r12a** [comment]
Interestingly, and by coincidence, the Unicode Editorial Committee discussed this same topic wrt Unicode publications last week.  Their approach, which they are not planning to change, is to limit the list of 'editors' to the one or two persons who are actually caretakers of the document at the present time (ie. publishing and making or accepting current modifications).  They don't expect the list of editors to be more than a couple of people at any given time.

They prefer not to have a simple list that calls out authors because they say that it can be too difficult to define who should and who should not be in such a list.  They do, however, have carefully worded text in an Acknowledgements section that details who the contributors are and have been.  This allows them to be fairly specific about how the people acknowledged contributed to the document.

For example in Unicode® Standard Annex #14 Unicode Line Breaking Algorithm the [Acknowledgements](https://www.unicode.org/reports/tr14/tr14-51.html#Acknowledgments) section describes the original author of the document, and subsequent major contributors and editors (with dates); it lists people who have provided 'background information', people who have done reviews, and people who have contributed text or ideas for specific sections.

A problem with the Unicode approach in my mind (and that of a few others) is that the Acknowledgements section is hidden at the bottom of the document, and probably not read by many people.  I would suggest that that section should be right at the top of the document, or at the very least a prominent link to it should feature in the set of links at the top of the document.

It was also pointed out that the chain of links to previous versions of the document allow those who really want to to figure out who was the editor in earlier versions of the document.  W3C documents, of course, have a similar set of links.

So this is a model that it may be worth looking into, as an alternative to a list of Authors.

**Comment by xfq** [comment]
After some discussions, I pushed a commit to add an Acknowledgment section at the beginning (before the Status of This Document section) and a link to the section in the spec metadata section. Any comment on this approach?

We can also consider writing the Acknowledgements section in more detail, like Bobby wrote the Introduction section, Eric wrote section xx.xx, Zhengyu wrote section xx.xx, Huijing provided a lot of translations, and so on and so forth.

**Comment by r12a** [comment]
Here's what occurred to me.

I was surprised that you'd managed to squeeze this in between the abstract and SOTD.  While that seems appropriate, unfortunately it looks a bit odd that the header starts with "1. " but is followed by an unnumbered SOTD (and slightly odd inter-section spacing).  I think we'd need to raise this with respec folks & spec design folks to resolve.

Also, i keep thinking that a better title for this section would be "Contributors", rather than "Acknowledgements".  The latter seems more like an afterthought, and the former seems more indicative of what we're setting out to do.

**Comment by r12a** [comment]
For the Khmer lreq doc i experimented with putting the acknowledgments section at the beginning of the introduction, and calling it 'Contributors'.   It seems not so bad...   https://w3c.github.io/sealreq/khmer/indexnew

**Comment by xfq** [comment]
> I was surprised that you'd managed to squeeze this in between the abstract and SOTD. While that seems appropriate, unfortunately it looks a bit odd that the header starts with "1. " but is followed by an unnumbered SOTD (and slightly odd inter-section spacing). I think we'd need to raise this with respec folks & spec design folks to resolve.

Agreed. If placed before SOTD, this section should be unnumbered.

> Also, i keep thinking that a better title for this section would be "Contributors", rather than "Acknowledgements". The latter seems more like an afterthought, and the former seems more indicative of what we're setting out to do.

+1

> For the Khmer lreq doc i experimented with putting the acknowledgments section at the beginning of the introduction, and calling it 'Contributors'. It seems not so bad... https://w3c.github.io/sealreq/khmer/indexnew

Looks good to me. This is another approach, and does not require respec to change their code. I wonder what other people think?

**Comment by xfq** [comment]
Merging per https://www.w3.org/2024/05/08-clreq-minutes.html#t03

**Pull request merged**
