### PR TITLE
Fix #494

### LINKED ISSUE #494: 关于 3.1.1.2 中间隔号用法的表述细节
https://w3c.github.io/clreq/#id86

> 间隔号为中文标点，当外语姓名包含西文首字母缩写作为单节时，原则上西文字母后面应该使用西文句点［……］

其中「西文首字母缩写作为单节」一句，「单节」一词的表意可能不够明确。中文书写通常不强调分词或分节，此处「单节」可能需要更明确的定义，或改用其他更通俗易懂的表述方式？

该句的英语翻译，也没有提到「首字母缩写」或「单节」相关的内容/术语，表意上与中文不够一致。

### PR DESCRIPTION
**Pull request by realfish**
This revision is based on the issue #494 and the discussion on the editors’ meeting on 18 Oct 2022.

Changed:

* Update SC & TC copy per [#494](https://github.com/w3c/clreq/issues/494#issuecomment-1281916860).
* Use fullwidth Latin letter and fullwidth full stop in the examples.
* ~~Change a “but” into “while” per editors’ meeting on 29 Nov 2022.~~ Revert this change per editors’ meeting on 18 Jan 2023.

The related English translation need to be confirmed.

***
<a href="https://pr-preview.s3.amazonaws.com/realfish/clreq/pull/501.html" title="Last updated on Feb 1, 2023, 11:12 AM UTC (77f7626)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/501/6fd8d73...realfish:77f7626.html" title="Last updated on Feb 1, 2023, 11:12 AM UTC (77f7626)">Diff</a>

### CODE REVIEW

**Comment by xfq** [comment]
英文版的最后一句是：

```html
For example, <span lang="zh-hant">比尔·盖茨</span> but <span lang="zh-hant">B. 盖茨</span>.
```

我有两点建议：

1. 这里的“比尔·盖茨”应为“比爾·蓋茲”（“尔”和“盖”的字形不对，关于“茨”vs“茲”，我个人觉得都行）；
2. 这句话似乎不太通顺，需要重写一下。

**Comment by realfish** [comment]
英文中的繁体中文「比爾」已修正，见 a889539。

「For example, 比爾·蓋茨 but Ｂ．盖茨.」这句话我第一次读也觉得有点不顺，不过语义上也说不出明确的错误，所以暂时没有改动它。猜测这里「but」是想突出「对比」前后两个例子中符号使用的差异。可以请其他编辑也再看一下。

**Comment by r12a** [comment]
Fwiw, to me the 'but' should be retained.  If you want to use 'while' you'd need to add a bunch of other words too, such as 'while B. Gates uses a full stop'.  ('Whereas' would be better than 'while', but for me 'but' is the cleanest way to say it. hth

**Comment by xfq** [comment]
We should probably remove the `class="checkme"` for the English text. @r12a any comments?

**Comment by r12a** [comment]
No comments.

**Comment by xfq** [comment]
Merging. Thank you, @realfish and @r12a!

**Pull request merged**
