### PR TITLE
Add image for solid setting

### PR DESCRIPTION
**Pull request by xfq**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/pull/596.html" title="Last updated on Feb 22, 2024, 1:38 PM UTC (4a8b55a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clreq/596/4d21ac5...4a8b55a.html" title="Last updated on Feb 22, 2024, 1:38 PM UTC (4a8b55a)">Diff</a>

### CODE REVIEW

**Comment by r12a** [comment]
@xfq, since there's a little descriptive text in the SVG image, we may need to add an english version (and TC?) of the image.  Alternatively, you could replace the descriptive text with something like 🅐 and put the explanation in the caption.

**Comment by xfq** [comment]
@r12a Thanks. Should be fixed now.

**Comment by xfq** [comment]
Just merged them into one image again per https://www.w3.org/2024/02/21-clreq-minutes.html#t04

**Comment by xfq** [comment]
Merging per https://www.w3.org/2024/03/27-clreq-minutes.html#t03

**Pull request merged**
