### PR TITLE
Add Hui Jing as an editor

### PR DESCRIPTION
**Pull request by xfq**
Hui Jing did some proofreading, translation, and other fixes. I'm wondering if we can add her as a co-editor of this document, @r12a?

@huijing Thanks for your contribution!

### CODE REVIEW

**Comment by r12a** [comment]
Seems a good idea to me.  Thanks @huijing !

**Comment by r12a** [comment]
We should check with Bobby, Ethan and Angel.

**Comment by xfq** [comment]
They have agreed (in the latest telecon).

**Comment by r12a** [comment]
Great, let's do it.

**Review by huijing — APPROVED** [review]

**Pull request merged**
